### ISSUE TITLE
icons and art improvements 

### ISSUE THREAD

**Issue by ammar-faifi** [petroly-initiative/petroly-react#243]
- [x] The left side art is so huge takes fraction of seconds to be loaded
<img width="292" alt="Screen Shot 2022-06-11 at 17 51 15" src="https://user-images.githubusercontent.com/65354445/173192822-7f94c44a-754a-4590-b848-4cd74202502f.png">

- [x] This icon is so pixel-ed 
<img width="111" alt="Screen Shot 2022-06-11 at 17 43 53" src="https://user-images.githubusercontent.com/65354445/173192565-5f0fc644-247e-4ac0-b557-f03d7ca39b1d.png">

- [x] the iPhone icon does not support png, that u can see filled with black background 

![WhatsApp Image 2022-06-11 at 5 46 40 PM](https://user-images.githubusercontent.com/65354445/173192810-12fd8b5d-0be8-4654-947f-416181641889.jpeg)

**Comment by Muhab2001** [comment]
Pardon me for ignoring this issue, I will work on it soon
