### ISSUE TITLE
Support the `cursor-based` pagination

### ISSUE THREAD

**Issue by ammar-faifi** [petroly-initiative/petroly-react#269]
we have been using the `offset-based pagination` so far.  As working on #258, I found the new API does not provide good functionality , for our front end design, e.g., does not return the total `count`. this make it hard to implement numbered buttons pagination.

so we are going to use `Relay`  support, i.e., `cursor-based` pagination.

doing so it permits the front end designers to use any techniques for the pagination buttons:
- numbered buttons (current)
- prev & next buttons only
- load more button (encouraged)

**Comment by ammar-faifi** [comment]
moreover `Apollo Client` has very amazing support for `cursor-based` pagination 
here: https://www.apollographql.com/docs/react/pagination/core-api

**Comment by Muhab2001** [comment]
I've read about different types of pagination options online, and `cursor-based` pagination seems like a good fit, especially for the notifier service.

**Comment by ammar-faifi** [comment]
it's done in #258
