### ISSUE TITLE
Course modal is extended along the page

### ISSUE THREAD

**Issue by ammar-faifi** [petroly-initiative/petroly-react#282]
I can't see the lower part of the course modal 

<img width="841" alt="Screen Shot 2022-07-26 at 11 09 42" src="https://user-images.githubusercontent.com/65354445/180956999-7432607c-046d-4b40-841c-c74c8b100802.png">

this part is at the end of the page

<img width="904" alt="Screen Shot 2022-07-26 at 11 09 46" src="https://user-images.githubusercontent.com/65354445/180957179-ad53d269-e62c-4abf-906f-d256d98dcd6c.png">

**Comment by Muhab2001** [comment]
Can't you scroll it? I did this because it gives a better interpretation of more elements to be scrolled

**Comment by ammar-faifi** [comment]
@Muhab2001 

https://user-images.githubusercontent.com/65354445/180984484-ca003565-a6f6-4b5e-a927-f5bee020be27.mov

**Comment by Muhab2001** [comment]
Yup, that's a big yikes, I am reverting it back.
