### ISSUE TITLE
let the phone users know there is more services cards to scroll

### ISSUE THREAD

**Issue by ammar-faifi** [petroly-initiative/petroly-react#289]
![IMG_7F1B7C7EEA90-1](https://user-images.githubusercontent.com/65354445/182434038-d0e349c5-270f-4a48-aef0-420e601b1620.jpeg)

it appears that there's only one card, users might get tricked and not scroll for more

**Comment by ammar-faifi** [comment]
@Muhab2001 
Another issue here is that the very top part color does not match the page theme

other websites that I visit does so

**Comment by Muhab2001** [comment]
I actually changed the color of the status bar recently in `manifest.json`. I believe this color is way more subtle than our aggressive brand color

**Comment by ammar-faifi** [comment]
this https://github.com/petroly-initiative/petroly-react/issues/289#issuecomment-1203035842 is still not fixed
