### ISSUE TITLE
iPhone navbar does not match the page theme

### ISSUE THREAD

**Issue by ammar-faifi** [petroly-initiative/petroly-react#291]
@Muhab2001 
Another issue here is that the very top part color does not match the page theme

other websites that I visit does so

prop sol: https://stackoverflow.com/questions/48876033/iphone-x-status-bar-black-web-app

_Originally posted by @ammar-faifi in https://github.com/petroly-initiative/petroly-react/issues/289#issuecomment-1203035842_

**Comment by ammar-faifi** [comment]
![output](https://user-images.githubusercontent.com/65354445/182797530-a0904773-35e4-4293-b1ae-6f2601aef6ce.gif)

**Comment by Muhab2001** [comment]
I used an apple-specific meta tag to make it black all the time. Close the issue if it functions correctly

**Comment by ammar-faifi** [comment]
fixed
