### ISSUE TITLE
`FIN` department does not exist

### ISSUE THREAD

**Issue by Muhab2001** [petroly-initiative/petroly-react#297]
I believe this department has also become a part of `ACFN`

**Comment by ammar-faifi** [comment]
This department `ACFN` was added as per https://github.com/petroly-initiative/petroly-django/issues/94.

`FIN` will be delete after deploying `notifier` into `main`. Because in production we have instructors in `FIN`, 
deleting it then deploying will cause issue

**Comment by ammar-faifi** [comment]
fixed
