### ISSUE TITLE
user can confirm settings without login with telegram

### ISSUE THREAD

**Issue by ammar-faifi** [petroly-initiative/petroly-react#315]
<img width="517" alt="Screen Shot 2022-08-18 at 21 46 47" src="https://user-images.githubusercontent.com/65354445/185471096-84437149-5a64-4a7b-8cb0-66c0dcd3edd8.png">

as u can see this is first-time setup, I chose Telegram but I didn't click the "Log in with Telegram" and I still can click `Confirm`

this should be prevented

**Comment by ammar-faifi** [comment]
This https://github.com/petroly-initiative/petroly-django/commit/d04cde6ea8249775fafb11da9d8c1fae99d5fd38 will raise an exception you can say it's simple warning

**Comment by Muhab2001** [comment]
Yup, sending a confirmation/error from the backend is the optimal solution, because users already signed-in with their telegram are also eligible to confirm without the user hash available
