### ISSUE TITLE
non-matched rating start after searching

### ISSUE THREAD

**Issue by ammar-faifi** [petroly-initiative/petroly-react#332]
after searching for a instructor the result has the same previous cards starts patterns 

<img width="1817" alt="Screen Shot 2022-08-28 at 19 28 04" src="https://user-images.githubusercontent.com/65354445/187086386-6c3d76be-4573-4455-977f-f5140988dc4d.png">

**Comment by Muhab2001** [comment]
The list elements were missing the `key` attribute. All clear
